version: '3.8'

services:
  springboot-app:
    build:
      context: ./Expenses-Tracker-WebApp
      dockerfile: Dockerfile
    image: rags/expenses-tracker-app:latest
    container_name: springboot-app
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ecommerce_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./Expenses-Tracker-WebApp/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - springboot-app
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge  
